### PR TITLE
Renew italian translation

### PR DESCRIPTION
**Pull request by unbranched**

### CODE REVIEW

**Comment by MenosGrante** [comment]
Greetings @unbranched, could you update your translation to follow latest strings.xml update? It will be included in 2.4 update.

**Comment by unbranched** [comment]
@MenosGrante it's already this indeed :)

**Comment by MenosGrante** [comment]
@unbranched I have added few new strings few days ago.

**Comment by unbranched** [comment]
Ok done, I missed two strings.

**Pull request merged**
