### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by javito1081**
[Rekado_NVS.zip](https://github.com/MenosGrante/Rekado/files/2546569/Rekado_NVS.zip)
Spanish translation for strings.xml, also i include an apk that serves as a shortcut for people using the nvidia shield as a device to load the payload into their switchs, this shortcut will allow Rekado to show up in nvidia shield tv menu for use.

### CODE REVIEW

**Comment by MenosGrante** [comment]
Well, what have you changed in your APK? I can merge it in main branch after review, so you can add it in your pull request.

Also, please do not create separate pull requests for single file.

**Comment by javito1081** [comment]
I didn't change anything, I created that APK as a shortcut, u still need to
install ur app plus the one I gave u for Nvidia shield to serve as a
shortcut menu for ur APK :-)

**Comment by javito1081** [comment]
I'm sorry if I did something wrong it's the first time I upload something
into that place, in fact I just registered on the site yesterday to do that
for u, inlocenur APK :-)

**Comment by MenosGrante** [comment]
@javito1081 No problem, I will merge it anyway, thank you!

**Pull request closed without merging**
