### PR TITLE
Brazilian Portuguese localization.

### PR DESCRIPTION
**Pull request by DavidOliM**

### CODE REVIEW

**Comment by MenosGrante** [comment]
@DavidOliM Hello and thank you for your PR. But could you also translate one more strings.xml file in `Rekado\konae\src\main\res`

**Comment by DavidOliM** [comment]
Sure, done.

**Comment by MenosGrante** [comment]
@DavidOliM Great, I will merge it now and it will be available in next update.

**Comment by MenosGrante** [comment]
Hi, @DavidOliM, I wanted to notify you, that new strings for 3.0 update were loaded to new place for localization - https://rekundevelopment.oneskyapp.com/collaboration/project?id=336657. It would be good if you could update it there. "Pull requests" localization will beclined now.

**Comment by DavidOliM** [comment]
@MenosGrante Sure, it's done now.
Though I was wondering if there is a way i can test the app with the new translated strings without having to compile it?

**Comment by MenosGrante** [comment]
@DavidOliM I guess I can build something like RC build for you, but I need to know, where I can send it for you.

P.S. I had to update localization one more time, because I have missed some strings in code. Could you update it one more time in OneSky?

**Comment by DavidOliM** [comment]
Done. I translated a few lines from Portugal's translation too although a native could check that for grammar accuracy.
If you can build the app for me to test, you can send it to me through this e-mail: dd09david@gmail.com

**Comment by DavidOliM** [comment]
Alright, i tested the app and everything seems to be good. Thanks! 👍

**Pull request merged**
