### PR TITLE
updated french translation

### PR DESCRIPTION
**Pull request by tiliarou**

### CODE REVIEW

**Comment by MenosGrante** [comment]
Hi, @tiliarou, I wanted to notify you, that new strings for 3.0 update were loaded to new place for localization - https://rekundevelopment.oneskyapp.com/collaboration/project?id=336657. It would be good if you could update it there. "Pull requests" localization will beclined now.

**Comment by tiliarou** [comment]
I corrected a few stuff and added the missing parts

**Comment by MenosGrante** [comment]
Sorry @tiliarou, I had to update localization one more time, because I have missed some strings in code. Could you update it one more time in OneSky?

**Comment by tiliarou** [comment]
No worries. It's done.

**Pull request merged**
