### PR TITLE
Polish Translation

### PR DESCRIPTION
**Pull request by mixon606**

### CODE REVIEW

**Comment by MenosGrante** [comment]
Wow, thank you @mixon606!

But, you have to translate one more file (\app\src\main\res\values\arrays.xml) before localization. Could you finish it and I will merge it after that.

**Comment by mixon606** [comment]
I don't see a file under that name

**Comment by MenosGrante** [comment]
Oh, my fault, i forgot, that I have removed it.

**Comment by MenosGrante** [comment]
Hi, @mixon606, I wanted to notify you, that new strings for 3.0 update were loaded to new place for localization - https://rekundevelopment.oneskyapp.com/collaboration/project?id=336657. It would be good if you could update it there. "Pull requests" localization will beclined now.

**Comment by mixon606** [comment]
All done

**Comment by MenosGrante** [comment]
Sorry @mixon606, I had to update localization one more time, because I have missed some strings in code. Could you update it one more time in OneSky?

**Pull request merged**
