### PR TITLE
Add Bahasa Indonesia Translation

### PR DESCRIPTION
**Pull request by wendyliga**
Indonesia Translation

### CODE REVIEW

**Comment by MenosGrante** [comment]
Why did you modified original strings? Remove you modifications from **values/strings.xml** and I will merge your localization. Thank you!

**Comment by wendyliga** [comment]
I dont mean to changed it 

Sorry i dont fix my repo , because i have work to do this past week

**Comment by MenosGrante** [comment]
@wendyliga I have already fixed it, no problem.

**Comment by MenosGrante** [comment]
Hi, @wendyliga, I wanted to notify you, that new strings for 3.0 update were loaded to new place for localization - https://rekundevelopment.oneskyapp.com/collaboration/project?id=336657. It would be good if you could update it there. "Pull requests" localization will beclined now.

**Pull request merged**
